package catan.API.response;

public enum Code {
    RolledSeven,
    RolledNotSeven,
    PlayerNoLumber,
    PlayerNoWool,
    PlayerNoGrain,
    PlayerNoBrick,
    PlayerNoOre,
    NoRoad,
    NoSettlement,
    NoCity,
    BankNoLumber,
    BankNoWool,
    BankNoGrain,
    BankNoBrick,
    BankNoOre,
    BankNoRoad,
    BankNoSettlement,
    BankNoCity,
    BankNoDev,
    IntersectionAlreadyOccupied,
    NotTwoRoadsDistance,
    SameTile,
    NoSuchIntersection,
    RoadAlreadyExistent,
    RoadInvalidPosition,
    RoadStartNotOwned,
    InvalidCityPosition,
    NotEnoughResources,
    InvalidSettlementPosition,

}
