package catan.API.response;

public enum Code {
    RolledSeven,
    RolledNotSeven,
    PlayerNoLumber,
    PlayerNoWool,
    PlayerNoGrain,
    PlayerNoBrick,
    PlayerNoOre,
    PlayerHasDev,
    PlayerNoDev,
    MonopolySuccess,
    KnightSuccess,
    RoadBuildingSuccess,
    YearOfPlentySuccess,
    ResourceNotSet,
    FirstResourceNotSet,
    SecondResourceNotSet,
    PlayerNoResource,
    NoRoad,
    NoSettlement,
    NoCity,
    BankNoLumber,
    BankNoWool,
    BankNoGrain,
    BankNoBrick,
    BankNoOre,
    BankNoRoad,
    BankNoSettlement,
    BankNoCity,
    BankNoDev,
    BankNoResource,
    IntersectionAlreadyOccupied,
    NotTwoRoadsDistance,
    SameTile,
    NoSuchIntersection,
    RoadAlreadyExistent,
    RoadInvalidPosition,
    RoadStartNotOwned,
    InvalidCityPosition,
    NotEnoughResources,
    InvalidSettlementPosition,
    TradeIsDone,
    InvalidTradeRequest,

}
